### ISSUE TITLE
reproducibility

### ISSUE THREAD

**Issue by selimfirat** [desResLab/LINFA#12]
JOSS guidelines require reproducibility of the results in the paper. Could you please elaborate on this, and also can you indicate this matter in the paper?

JOSS review point: "If the paper contains original results, results are entirely reproducible by reviewers."

**Comment by daneschi** [comment]
Thanks for the comments. Sure, the paper discusses a number of features unique to the LINFA library (specifically, an adaptive surrogate model and the adaptive selection of annealing increments) and the appendix contains a detailed description of a number of tests cases. To make sure these results are reproducible, we have included all tests cases in this GitHub repository. It is possible to run these cases simply following the instructions reported either in the "readme.md" file or in the "Numerical Benchmark" section of the paper. Hope this answers your questions, otherwise please let us know for any further questions you may have. Thanks Again.
